### PR TITLE
MapInfoBox was closing annoyingly after you left initial map then opened new one

### PR DESCRIPTION
**Pull request by Connoropolous**
this is the same as on the initial page load (what happens in the 'init' function)

### CODE REVIEW

**Review by devvmh — COMMENTED** [review]
Why isn't this being removed from somewhere else?

**Comment by Connoropolous** [comment]
cause it's the intended behaviour. We have a click event listener on 'body' which is designed to close the mapInfoBox, but mapInfoBox needs to stopPropogation to keep from closing itself when you click around on it. 

Similar to what we do in react with clickOutsideDiv

**Comment by Connoropolous** [comment]
mapInfoBox unfortunately is not in react yet. It's up next

**Comment by devvmh** [comment]
Ok lgtm ship it

**Comment by Connoropolous** [comment]
fixes #1146

**Pull request merged**
