### PR TITLE
ability to select/unselect all metacodes in custom set with keyboard shortcut (fix #390)

### LINKED ISSUE #390: [SWITCH METACODES] when on 'custom' selection, allow user to toggle them ALL on or off
when you have the metacode carousel up, and you click on the little gear icon, it brings up the metacode selection panel. If you switch to the `custom` tab, you should be able to hit a button (there is no buttons yet) that selects all of them, or deselects all of them, so that you can much more quickly create the custom set that you want.

### PR DESCRIPTION
**Pull request by devvmh**

### CODE REVIEW

**Comment by Connoropolous** [comment]
This is great! What inspired it? Also, want to take an additional minute to add two buttons to the UI that call the same function?

**Comment by devvmh** [comment]
Yeah sure i can do that

Its been on my list of assigned issues for a long time haha, I decided to kill one this morning because I'm paused in file uploads

**Comment by Connoropolous** [comment]
@devvmh code looks good to me. do you feel its done? merge it in?

**Comment by devvmh** [comment]
Doooo it

**Pull request merged**
