### PR TITLE
Fix/pan.close.filterbox

### PR DESCRIPTION
**Pull request by Bortseb**

### CODE REVIEW

**Comment by devvmh** [comment]
I'm still not sure I like this change. What if I want to pan around while filtering? It's kind of like pinning open the topic carousel - you leave it open and pan around while doing operations.

I think we should fix the click-pan issue instead

**Comment by Bortseb** [comment]
Maybe this issue needs broader input then? To try and determine which option is more likely to be what the user expects... and to determine what is more likely, 1. that the user chooses some filters and then expects the box to go away once they resume mapping, or 2. That they more often like to keep the filter box open and pan around while they are adding filters. (And having to keep opening it is more annoying)

**Comment by devvmh** [comment]
@Bortseb should we close this?

**Comment by Bortseb** [comment]
sure, how things work now are good... i feel like we need a section for obscure options/tweaks for power users lol

**Pull request closed without merging**
