### PR TITLE
Made DEL key an alternative for deleting selected entities

### PR DESCRIPTION
**Pull request by Bortseb**

### CODE REVIEW

**Comment by Bortseb** [comment]
see #969 for context

**Comment by Connoropolous** [comment]
hm, I didn't get notified of this request for review. interesting. 

I will check it out locally on my computer, because the code looks fine, but I want to make sure I/we aren't missing anything. Nice Rob!

**Comment by Bortseb** [comment]
Maybe you weren't notified @Connoropolous because I didn't add you at the time of creation... but instead added you after once a few days went by and I wasn't sure if anyone saw this little addition.... So maybe pings like this one are better?

**Comment by Connoropolous** [comment]
@Bortseb in the cases of this proposal going through, lets change this to perform the `remove` action instead of `delete`
https://metamaps.slack.com/archives/metamaps-cc/p1481736452000162

So let's wait a little longer before merging

**Pull request closed without merging**
