### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JohnGillanders**
Added example of cloning repository using https:// protocol instead of SSH protocol - this is simpler to do since no set-up of SSH keys is required.

### CODE REVIEW

**Comment by Connoropolous** [comment]
Hi @JohnGillanders, thanks for this! I'll merge it. Were you able to get it running locally, if that's what you were trying to do?

**Comment by JohnGillanders** [comment]
Hi Connor,

Thanks. :)
My friend (CCed here) and I are learning Metamaps because we’d like to contribute to it.

We are indeed trying to run it locally (MacBook Pro) and on my web host (A Small Orange Gnu/Linux hosting), but have not managed to do that so far (have hit various software installation/dependency issues - even using the VM hasn’t worked so far).

The next thing we plan to try is installing Ubuntu on a spare machine and following the Ubuntu installation instructions.

Regards,
John Gillanders

Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology
+64 27 486 1533 (New Zealand)

**Comment by Connoropolous** [comment]
Hey @johngillanders! Sorry it's taken me a few days, I've been running a program for teens this last week! 

I really want to help you get set up, and feeling able to contribute :) can you tell me where you got hung up? At the same time, I'll review the documentation and see if I can see any obvious holes.

**Comment by JohnGillanders** [comment]
Hi Connor,

Thanks a lot for your reply and sorry for my delay in replying back.

We ended up deciding to install Ubuntu on a spare computer and making that accessible on the internet via my home fibre connection for our development & testing (i.e. ‘playing around’ at this stage).

This worked and the server is up and running with Metamaps, everything worked fine up until the steps for running the realtime server (see Ubuntu installation instructions <https://github.com/metamaps/metamaps/blob/develop/doc/UbuntuInstallation.md>):

cd realtime
npm install
<worked okay apart from the following warnings:>
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2


technaturally@Metamaps-Test:~$ node realtime-server.js
module.js:328
    throw err;
    ^

Error: Cannot find module '/home/technaturally/realtime-server.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Running Ubuntu 16.04.2 LTS (GNU/Linux 4.8.0-58-generic i686) on a rather old Mac Mini (Intel Core Duo 32-bit processor, 2 Gb RAM, plenty of free disk space)

Any idea what to do to fix that?

Metamaps seems to run mostly okay anyway, but a couple of things don’t seem to work quite right, which I assume is because of the realtime server not running.

Regards,
John Gillanders

Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology

**Comment by devvmh** [comment]
Hey @JohnGillanders 

The error message you've got is because node can't find the realtime-server.js file. In the terminal, change directory to the folder that holds the metamaps code, then`cd realtime` to enter the realtime directory. Then `node realtime-server.js` should work.

For example, if you cloned metamaps to /home/technaturally/metamaps, you could run

```
cd /home/technaturally/metamaps/realtime
node realtime-server.js
```

If that doesn't work post back and I can suggest more things

**Comment by JohnGillanders** [comment]
Hi Devin,

Oops, I copied & pasted the wrong error message. I had figured that one out, but then got the following error when running node realtime-server.js from within the ‘realtime’ folder:
technaturally@Metamaps-Test:~/metamaps/realtime$ node realtime-server.js
/home/technaturally/metamaps/realtime/realtime-server.js:8
const { createStore } = require('redux')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Your help with what is causing this would be much appreciated.

Regards,
John Gillanders

Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology
+64 27 486 1533 (New Zealand)

**Comment by Connoropolous** [comment]
my turn this time (Devin beat me to responding) :P 

this error has to do with a mismatch between the node version you're running, and the version the code is written in. We'll have to specify that somewhere. If you use anything above node 6.11.1 it should work.

**Comment by Connoropolous** [comment]
if you use nvm (node version manager) it's easy to switch, highly recommended.

**Comment by JohnGillanders** [comment]
Thanks, Connor, much appreciated.

I'll update node when I get a chance and will let you know how it goes.
Thanks for the tip about using NVM too.

Regards,
John Gillanders

**Comment by JohnGillanders** [comment]
Hi again Connor,

I also want to run metamaps on my Mac through the virtual machine as mentioned in the ReadMe file.

I have the virtual machine running, but what is the login and password for the vagrant image? Thanks.


Regards,
John Gillanders

Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology
+64 27 486 1533 (New Zealand)

**Comment by Connoropolous** [comment]
Hey :) I think there shouldn't be one... you should just be able to do the
usual
'vagrant up' and 'vagrant ssh'

**Comment by JohnGillanders** [comment]
Hi Connor,

Seems like I used the wrong terminology, I meant the password for the user to log in to Gnu/Linux on the virtual machine. I tried the same user name and password as for MetaMaps but it didn't seem to work.

Maybe I missed this info in the docs.

Regards,
John

Mobile: 027 486 1533

**Pull request merged**
